### ISSUE TITLE
Can you please update benefit of using Vuefire over not using it?

### ISSUE THREAD

**Issue by xerosanyam** [kangsLee/VueFire6Pack-Demo#1]
I found only your repo using Vuefire + webpack + Vue-cli on github. Since I am using the same configuration, it was very helpful. 
However I am unclear why vuefire is required, can you please mention it somewhere so people(including me) can have clear understanding :)
Thanks

**Comment by kangsLee** [comment]
Hi, @xerosanyam.
I have two kinds of brunch.
- [Demo without VueFire](https://github.com/kangsLee/VueFire6Pack-Demo/tree/VueFire)
- [Demo with VueFire](https://github.com/kangsLee/VueFire6Pack-Demo/tree/VueFire)

I started with VueFire, but soon I removed VueFire.
Because there are version management issues. And it is hard to operate freely.

Currently, I don't need VueFire, but I expect updates.

If this helps, I'll update README.md.

Thnaks.

**Comment by xerosanyam** [comment]
Hello. I looked into the branches, but it was still not very clear to me.
The only diff b/w the branches was:
```
// in Vuefire
firebase: {
  todos: todosRef.limitToLast(25),
}

// without Vuefire
todosRef.limitToLast(25).on('value', (snapshot) => {
  this.todos = snapshot.val();
});
```
I guess the use of vuefire is to reduce code complexity and make it simpler :smile:

**Comment by kangsLee** [comment]
Oh, I see. I agree with you.
I tried to add auth or other features via firebase, but now only VueFire has been removed.
So, VueFire is better for current projects.

If you are using the firebase database, I think you should use VueFire to write it in a concise syntax. (only database)
